robot:
  start_position: [0.0, 0.0, 0.0]  # Initial robot base position [x, y, z]
  start_orientation: [0.0, 0.0, 0.0]  # Initial robot base orientation [roll, pitch, yaw]
  initial_joint_positions: [0.0, -0.8, 0.0, -1.8, 0.0, 1.5, 0.0]  # New joint angles to extend the arm outward

rope:
  length: 0.5  # Length of the rope in meters
  num_segments: 15  # Number of segments in the rope
  segment_radius: 0.01  # Radius of each rope segment
  segment_mass: 0.01 # Mass of each rope segment
  start_position: [0.5, 0.5, 1.0]  # Start position of the first rope segment

simulation:
  gravity: [0, 0, -9.81]  # Gravity in the simulation
  time_step: 0.0041667  # Time step for the simulation loop
  duration: 10  # Duration of the simulation

trajectory:
  amplitude: 0.2 # Amplitude of the oscillating motion
  frequency: 0.4 # Frequency of the oscillation
